<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    protected $tableName = 'countries';
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table($this->tableName)->truncate();

        DB::table($this->tableName)->insert([
            0 => [
                'name' => 'Беларусь',
                'code' => 'BY',
                'mask' => '+375(__)___-__-__',
                'img' => '/img/flags/by.svg',
                'prefix' => '+375',
            ],
            1 => [
                'name' => 'Россия',
                'code' => 'RU',
                'mask' => '+7(___)___-__-__',
                'img' => '/img/flags/ru.svg',
                'prefix' => '+7',
            ],
            2 => [
                'name' => 'Казахстан',
                'code' => 'KZ',
                'mask' => '+7(7__)___-__-__',
                'img' => '/img/flags/kz.svg',
                'prefix' => '+77',
            ],
            3 => [
                'name' => 'Украина',
                'code' => 'UA',
                'mask' => '+380(__)___-__-__',
                'img' => '/img/flags/ua.svg',
                'prefix' => '+380',
            ],
            4 => [
                'name' => 'Австралия',
                'code' => 'AU',
                'mask' => '+61-_-____-____',
                'img' => '/img/flags/au.svg',
                'prefix' => '+672',
            ],
            5 => [
                'name' => 'Австрия',
                'code' => 'AT',
                'mask' => '+43(___)___-____',
                'img' => '/img/flags/at.svg',
                'prefix' => '+43',
            ],
            6 => [
                'name' => 'Азербайджан',
                'code' => 'AZ',
                'mask' => '+994-__-___-__-__',
                'img' => '/img/flags/az.svg',
                'prefix' => '+994',
            ],
            8 => [
                'name' => 'Албания',
                'code' => 'AL',
                'mask' => '+355(___)___-___',
                'img' => '/img/flags/al.svg',
                'prefix' => '+355',
            ],
            9 => [
                'name' => 'Алжир',
                'code' => 'DZ',
                'mask' => '+213-__-___-____',
                'img' => '/img/flags/dz.svg',
                'prefix' => '+213',
            ],
            10 => [
                'name' => 'Виргинские Острова (США)',
                'code' => 'VI',
                'mask' => '+1(340)___-____',
                'img' => '/img/flags/vi.svg',
                'prefix' => '+1340',
            ],
            11 => [
                'name' => 'Американское Самоа',
                'code' => 'AS',
                'mask' => '+1(684)___-____',
                'img' => '/img/flags/as.svg',
                'prefix' => '+1684',
            ],
            12 => [
                'name' => 'Ангилья',
                'code' => 'AI',
                'mask' => '+1(264)___-____',
                'img' => '/img/flags/ai.svg',
                'prefix' => '+1264',
            ],
            13 => [
                'name' => 'Ангола',
                'code' => 'AO',
                'mask' => '+244(___)___-___',
                'img' => '/img/flags/ao.svg',
                'prefix' => '+244',
            ],
            14 => [
                'name' => 'Андорра',
                'code' => 'AD',
                'mask' => '+376-___-___',
                'img' => '/img/flags/ad.svg',
                'prefix' => '+376',
            ],
            15 => [
                'name' => 'Антарктида',
                'code' => 'AQ',
                'mask' => '+672-1__-___',
                'img' => '/img/flags/aq.svg',
                'prefix' => '+672',
            ],
            16 => [
                'name' => 'Антигуа и Барбуда',
                'code' => 'AG',
                'mask' => '+1(268)___-____',
                'img' => '/img/flags/ag.svg',
                'prefix' => '+1268',
            ],
            17 => [
                'name' => 'Аргентина',
                'code' => 'AR',
                'mask' => '+54(___)___-____',
                'img' => '/img/flags/ar.svg',
                'prefix' => '+54',
            ],
            18 => [
                'name' => 'Армения',
                'code' => 'AM',
                'mask' => '+374-__-___-___',
                'img' => '/img/flags/am.svg',
                'prefix' => '+374',
            ],
            19 => [
                'name' => 'Аруба',
                'code' => 'AW',
                'mask' => '+297-___-____',
                'img' => '/img/flags/aw.svg',
                'prefix' => '+297',
            ],
            20 => [
                'name' => 'Афганистан',
                'code' => 'AF',
                'mask' => '+93-__-___-____',
                'img' => '/img/flags/af.svg',
                'prefix' => '+93',
            ],
            21 => [
                'name' => 'Багамы',
                'code' => 'BS',
                'mask' => '+1(242)___-____',
                'img' => '/img/flags/bs.svg',
                'prefix' => '+1242',
            ],
            22 => [
                'name' => 'Бангладеш',
                'code' => 'BD',
                'mask' => '+880-__-___-___',
                'img' => '/img/flags/bd.svg',
                'prefix' => '+880',
            ],
            23 => [
                'name' => 'Барбадос',
                'code' => 'BB',
                'mask' => '+1(246)___-____',
                'img' => '/img/flags/bb.svg',
                'prefix' => '+1246',
            ],
            24 => [
                'name' => 'Бахрейн',
                'code' => 'BH',
                'mask' => '+973-____-____',
                'img' => '/img/flags/bh.svg',
                'prefix' => '+973',
            ],
            25 => [
                'name' => 'Белиз',
                'code' => 'BZ',
                'mask' => '+501-___-____',
                'img' => '/img/flags/bz.svg',
                'prefix' => '+501',
            ],
            26 => [
                'name' => 'Бельгия',
                'code' => 'BE',
                'mask' => '+32(___)___-___',
                'img' => '/img/flags/be.svg',
                'prefix' => '+32',
            ],
            27 => [
                'name' => 'Бенин',
                'code' => 'BJ',
                'mask' => '+229-__-__-____',
                'img' => '/img/flags/bj.svg',
                'prefix' => '+229',
            ],
            28 => [
                'name' => 'Бермуды',
                'code' => 'BM',
                'mask' => '+1(441)___-____',
                'img' => '/img/flags/bm.svg',
                'prefix' => '+1441',
            ],
            29 => [
                'name' => 'Болгария',
                'code' => 'BG',
                'mask' => '+359(___)___-___',
                'img' => '/img/flags/bg.svg',
                'prefix' => '+359',
            ],
            30 => [
                'name' => 'Боливия',
                'code' => 'BO',
                'mask' => '+591-_-___-____',
                'img' => '/img/flags/bo.svg',
                'prefix' => '+591',
            ],
            32 => [
                'name' => 'Босния и Герцеговина',
                'code' => 'BA',
                'mask' => '+387-__-_____',
                'img' => '/img/flags/ba.svg',
                'prefix' => '+387',
            ],
            33 => [
                'name' => 'Ботсвана',
                'code' => 'BW',
                'mask' => '+267-__-___-___',
                'img' => '/img/flags/bw.svg',
                'prefix' => '+267',
            ],
            34 => [
                'name' => 'Бразилия',
                'code' => 'BR',
                'mask' => '+55(__)____-____',
                'img' => '/img/flags/br.svg',
                'prefix' => '+55',
            ],
            36 => [
                'name' => 'Виргинские Острова (Великобритания)',
                'code' => 'VG',
                'mask' => '+1(284)___-____',
                'img' => '/img/flags/vg.svg',
                'prefix' => '+1284',
            ],
            37 => [
                'name' => 'Бруней',
                'code' => 'BN',
                'mask' => '+673-___-____',
                'img' => '/img/flags/bn.svg',
                'prefix' => '+673',
            ],
            38 => [
                'name' => 'Буркина-Фасо',
                'code' => 'BF',
                'mask' => '+226-__-__-____',
                'img' => '/img/flags/bf.svg',
                'prefix' => '+226',
            ],
            39 => [
                'name' => 'Бурунди',
                'code' => 'BI',
                'mask' => '+257-__-__-____',
                'img' => '/img/flags/bi.svg',
                'prefix' => '+257',
            ],
            40 => [
                'name' => 'Бутан',
                'code' => 'BT',
                'mask' => '+975-_-___-___',
                'img' => '/img/flags/bt.svg',
                'prefix' => '+975',
            ],
            41 => [
                'name' => 'Вануату',
                'code' => 'VU',
                'mask' => '+678-__-_____',
                'img' => '/img/flags/vu.svg',
                'prefix' => '+678',
            ],
            42 => [
                'name' => 'Ватикан',
                'code' => 'VA',
                'mask' => '+39-6-698-_____',
                'img' => '/img/flags/va.svg',
                'prefix' => '+379 / +39',
            ],
            44 => [
                'name' => 'Венгрия',
                'code' => 'HU',
                'mask' => '+36(___)___-___',
                'img' => '/img/flags/hu.svg',
                'prefix' => '+36',
            ],
            45 => [
                'name' => 'Венесуэла',
                'code' => 'VE',
                'mask' => '+58(___)___-____',
                'img' => '/img/flags/ve.svg',
                'prefix' => '+58',
            ],
            47 => [
                'name' => 'Восточный Тимор',
                'code' => 'TL',
                'mask' => '+670-___-____',
                'img' => '/img/flags/tl.svg',
                'prefix' => '+670',
            ],
            48 => [
                'name' => 'Вьетнам',
                'code' => 'VN',
                'mask' => '+84(___)____-___',
                'img' => '/img/flags/vn.svg',
                'prefix' => '+84',
            ],
            49 => [
                'name' => 'Габон',
                'code' => 'GA',
                'mask' => '+241-_-__-__-__',
                'img' => '/img/flags/ga.svg',
                'prefix' => '+241',
            ],
            50 => [
                'name' => 'Гаити',
                'code' => 'HT',
                'mask' => '+509-__-__-____',
                'img' => '/img/flags/ht.svg',
                'prefix' => '+509',
            ],
            51 => [
                'name' => 'Гайана',
                'code' => 'GY',
                'mask' => '+592-___-____',
                'img' => '/img/flags/gy.svg',
                'prefix' => '+592',
            ],
            52 => [
                'name' => 'Гамбия',
                'code' => 'GM',
                'mask' => '+220(___)__-__',
                'img' => '/img/flags/gm.svg',
                'prefix' => '+220',
            ],
            53 => [
                'name' => 'Гана',
                'code' => 'GH',
                'mask' => '+233(___)___-___',
                'img' => '/img/flags/gh.svg',
                'prefix' => '+233',
            ],
            55 => [
                'name' => 'Гватемала',
                'code' => 'GT',
                'mask' => '+502-_-___-____',
                'img' => '/img/flags/gt.svg',
                'prefix' => '+502',
            ],
            56 => [
                'name' => 'Гвиана',
                'code' => 'GF',
                'mask' => '+33 594-_____-____',
                'img' => '/img/flags/gf.svg',
                'prefix' => '+33 594',
            ],
            57 => [
                'name' => 'Гвинея',
                'code' => 'GN',
                'mask' => '+224-__-___-___',
                'img' => '/img/flags/gn.svg',
                'prefix' => '+224',
            ],
            58 => [
                'name' => 'Гвинея-Бисау',
                'code' => 'GW',
                'mask' => '+245-_-______',
                'img' => '/img/flags/gw.svg',
                'prefix' => '+245',
            ],
            59 => [
                'name' => 'Германия',
                'code' => 'DE',
                'mask' => '+49(____)___-____',
                'img' => '/img/flags/de.svg',
                'prefix' => '+49',
            ],
            61 => [
                'name' => 'Гибралтар',
                'code' => 'GI',
                'mask' => '+350-___-_____',
                'img' => '/img/flags/gi.svg',
                'prefix' => '+350',
            ],
            62 => [
                'name' => 'Гондурас',
                'code' => 'HN',
                'mask' => '+504-____-____',
                'img' => '/img/flags/hn.svg',
                'prefix' => '+504',
            ],
            63 => [
                'name' => 'Гонконг',
                'code' => 'HK',
                'mask' => '+852-____-____',
                'img' => '/img/flags/hk.svg',
                'prefix' => '+852',
            ],
            64 => [
                'name' => 'Гренада',
                'code' => 'GD',
                'mask' => '+1(473)___-____',
                'img' => '/img/flags/gd.svg',
                'prefix' => '+1473',
            ],
            65 => [
                'name' => 'Гренландия',
                'code' => 'GL',
                'mask' => '+299-__-__-__',
                'img' => '/img/flags/gl.svg',
                'prefix' => '+299',
            ],
            66 => [
                'name' => 'Греция',
                'code' => 'GR',
                'mask' => '+30(___)___-____',
                'img' => '/img/flags/gr.svg',
                'prefix' => '+30',
            ],
            67 => [
                'name' => 'Грузия',
                'code' => 'GE',
                'mask' => '+995(___)___-___',
                'img' => '/img/flags/ge.svg',
                'prefix' => '+995',
            ],
            68 => [
                'name' => 'Гуам',
                'code' => 'GU',
                'mask' => '+1(671)___-____',
                'img' => '/img/flags/gu.svg',
                'prefix' => '+1671',
            ],
            69 => [
                'name' => 'Дания',
                'code' => 'DK',
                'mask' => '+45-__-__-__-__',
                'img' => '/img/flags/dk.svg',
                'prefix' => '+45',
            ],
            71 => [
                'name' => 'Джибути',
                'code' => 'DJ',
                'mask' => '+253-__-__-__-__',
                'img' => '/img/flags/dj.svg',
                'prefix' => '+253',
            ],
            72 => [
                'name' => 'Доминика',
                'code' => 'DM',
                'mask' => '+1(767)___-____',
                'img' => '/img/flags/dm.svg',
                'prefix' => '+1767',
            ],
            73 => [
                'name' => 'Доминиканская Республика',
                'code' => 'DO',
                'mask' => '+1(___)___-____',
                'img' => '/img/flags/do.svg',
                'prefix' => '+1849',
            ],
            74 => [
                'name' => 'Демократическая Республика Конго',
                'code' => 'CD',
                'mask' => '+243(___)___-___',
                'img' => '/img/flags/cd.svg',
                'prefix' => '+243',
            ],
            76 => [
                'name' => 'Египет',
                'code' => 'EG',
                'mask' => '+20(___)___-____',
                'img' => '/img/flags/eg.svg',
                'prefix' => '+20',
            ],
            77 => [
                'name' => 'Замбия',
                'code' => 'ZM',
                'mask' => '+260-__-___-____',
                'img' => '/img/flags/zm.svg',
                'prefix' => '+260',
            ],
            79 => [
                'name' => 'Зимбабве',
                'code' => 'ZW',
                'mask' => '+263-_-______',
                'img' => '/img/flags/zw.svg',
                'prefix' => '+263',
            ],
            80 => [
                'name' => 'Израиль',
                'code' => 'IL',
                'mask' => '+972-_-___-____',
                'img' => '/img/flags/il.svg',
                'prefix' => '+972',
            ],
            81 => [
                'name' => 'Индия',
                'code' => 'IN',
                'mask' => '+91(____)___-___',
                'img' => '/img/flags/in.svg',
                'prefix' => '+91',
            ],
            82 => [
                'name' => 'Индонезия',
                'code' => 'ID',
                'mask' => '+62(8__)___-__-___',
                'img' => '/img/flags/id.svg',
                'prefix' => '+62',
            ],
            83 => [
                'name' => 'Иордания',
                'code' => 'JO',
                'mask' => '+962-_-____-____',
                'img' => '/img/flags/jo.svg',
                'prefix' => '+962',
            ],
            84 => [
                'name' => 'Ирак',
                'code' => 'IQ',
                'mask' => '+964(___)___-____',
                'img' => '/img/flags/iq.svg',
                'prefix' => '+964',
            ],
            85 => [
                'name' => 'Иран',
                'code' => 'IR',
                'mask' => '+98(___)___-____',
                'img' => '/img/flags/ir.svg',
                'prefix' => '+98',
            ],
            86 => [
                'name' => 'Ирландия',
                'code' => 'IE',
                'mask' => '+353(___)___-___',
                'img' => '/img/flags/ie.svg',
                'prefix' => '+353',
            ],
            87 => [
                'name' => 'Исландия',
                'code' => 'IS',
                'mask' => '+354-___-____',
                'img' => '/img/flags/is.svg',
                'prefix' => '+404',
            ],
            88 => [
                'name' => 'Испания',
                'code' => 'ES',
                'mask' => '+34(___)___-___',
                'img' => '/img/flags/es.svg',
                'prefix' => '+34',
            ],
            89 => [
                'name' => 'Италия',
                'code' => 'IT',
                'mask' => '+39(___)____-___',
                'img' => '/img/flags/it.svg',
                'prefix' => '+39',
            ],
            90 => [
                'name' => 'Йемен',
                'code' => 'YE',
                'mask' => '+967-___-___-___',
                'img' => '/img/flags/ye.svg',
                'prefix' => '+967',
            ],
            91 => [
                'name' => 'Кабо-Верде',
                'code' => 'CV',
                'mask' => '+238(___)__-__',
                'img' => '/img/flags/cv.svg',
                'prefix' => '+238',
            ],
            92 => [
                'name' => 'Острова Кайман',
                'code' => 'KY',
                'mask' => '+1(345)___-____',
                'img' => '/img/flags/ky.svg',
                'prefix' => '+1345',
            ],
            93 => [
                'name' => 'Камбоджа',
                'code' => 'KH',
                'mask' => '+855-__-___-___',
                'img' => '/img/flags/kh.svg',
                'prefix' => '+855',
            ],
            94 => [
                'name' => 'Камерун',
                'code' => 'CM',
                'mask' => '+237-____-____',
                'img' => '/img/flags/cm.svg',
                'prefix' => '+237',
            ],
            95 => [
                'name' => 'Канада',
                'code' => 'CA',
                'mask' => '+1(___)___-____',
                'img' => '/img/flags/ca.svg',
                'prefix' => '+1',
            ],
            96 => [
                'name' => 'Катар',
                'code' => 'QA',
                'mask' => '+974-____-____',
                'img' => '/img/flags/qa.svg',
                'prefix' => '+974',
            ],
            97 => [
                'name' => 'Кения',
                'code' => 'KE',
                'mask' => '+254-___-______',
                'img' => '/img/flags/ke.svg',
                'prefix' => '+254',
            ],
            98 => [
                'name' => 'Кипр',
                'code' => 'CY',
                'mask' => '+357-__-___-___',
                'img' => '/img/flags/cy.svg',
                'prefix' => '+357',
            ],
            99 => [
                'name' => 'Киргизия',
                'code' => 'KG',
                'mask' => '+996(___)___-___',
                'img' => '/img/flags/kg.svg',
                'prefix' => '+996',
            ],
            100 => [
                'name' => 'Кирибати',
                'code' => 'KI',
                'mask' => '+686-__-___',
                'img' => '/img/flags/ki.svg',
                'prefix' => '+686',
            ],
            101 => [
                'name' => 'Китайская Республика',
                'code' => 'TW',
                'mask' => '+886-_-____-____',
                'img' => '/img/flags/tw.svg',
                'prefix' => '+86',
            ],
            102 => [
                'name' => 'КНДР (Корейская Народно-Демократическая Республика)',
                'code' => 'KP',
                'mask' => '+850-____-_____________',
                'img' => '/img/flags/kp.svg',
                'prefix' => '+850',
            ],
            103 => [
                'name' => 'КНР (Китайская Народная Республика)',
                'code' => 'CN',
                'mask' => '+86-__-_____-_____',
                'img' => '/img/flags/cn.svg',
                'prefix' => '+86',
            ],
            105 => [
                'name' => 'Колумбия',
                'code' => 'CO',
                'mask' => '+57(___)___-____',
                'img' => '/img/flags/co.svg',
                'prefix' => '+57',
            ],
            106 => [
                'name' => 'Коморы',
                'code' => 'KM',
                'mask' => '+269-__-_____',
                'img' => '/img/flags/km.svg',
                'prefix' => '+269',
            ],
            107 => [
                'name' => 'Коста-Рика',
                'code' => 'CR',
                'mask' => '+506-____-____',
                'img' => '/img/flags/cr.svg',
                'prefix' => '+506',
            ],
            108 => [
                'name' => 'Кот-д’Ивуар',
                'code' => 'CI',
                'mask' => '+225-__-___-___',
                'img' => '/img/flags/ci.svg',
                'prefix' => '+225',
            ],
            109 => [
                'name' => 'Куба',
                'code' => 'CU',
                'mask' => '+53-_-___-____',
                'img' => '/img/flags/cu.svg',
                'prefix' => '+53',
            ],
            110 => [
                'name' => 'Кувейт',
                'code' => 'KW',
                'mask' => '+965-____-____',
                'img' => '/img/flags/kw.svg',
                'prefix' => '+965',
            ],
            111 => [
                'name' => 'Кюрасао',
                'code' => 'CW',
                'mask' => '+599-___-____',
                'img' => '/img/flags/cw.svg',
                'prefix' => '+5999',
            ],
            112 => [
                'name' => 'Лаос',
                'code' => 'LA',
                'mask' => '+856(20__)___-___',
                'img' => '/img/flags/la.svg',
                'prefix' => '+856',
            ],
            113 => [
                'name' => 'Латвия',
                'code' => 'LV',
                'mask' => '+371-__-___-___',
                'img' => '/img/flags/lv.svg',
                'prefix' => '+371',
            ],
            114 => [
                'name' => 'Лесото',
                'code' => 'LS',
                'mask' => '+266-_-___-____',
                'img' => '/img/flags/ls.svg',
                'prefix' => '+266',
            ],
            115 => [
                'name' => 'Либерия',
                'code' => 'LR',
                'mask' => '+231-__-___-___',
                'img' => '/img/flags/lr.svg',
                'prefix' => '+231',
            ],
            117 => [
                'name' => 'Ливия',
                'code' => 'LY',
                'mask' => '+218-__-___-___',
                'img' => '/img/flags/ly.svg',
                'prefix' => '+218',
            ],
            118 => [
                'name' => 'Литва',
                'code' => 'LT',
                'mask' => '+370(___)__-___',
                'img' => '/img/flags/lt.svg',
                'prefix' => '+370',
            ],
            119 => [
                'name' => 'Лихтенштейн',
                'code' => 'LI',
                'mask' => '+423(___)___-____',
                'img' => '/img/flags/li.svg',
                'prefix' => '+423',
            ],
            120 => [
                'name' => 'Люксембург',
                'code' => 'LU',
                'mask' => '+352(___)___-___',
                'img' => '/img/flags/lu.svg',
                'prefix' => '+352',
            ],
            121 => [
                'name' => 'Маврикий',
                'code' => 'MU',
                'mask' => '+230-___-____',
                'img' => '/img/flags/mu.svg',
                'prefix' => '+230',
            ],
            122 => [
                'name' => 'Мавритания',
                'code' => 'MR',
                'mask' => '+222-__-__-____',
                'img' => '/img/flags/mr.svg',
                'prefix' => '+222',
            ],
            123 => [
                'name' => 'Мадагаскар',
                'code' => 'MG',
                'mask' => '+261-__-__-_____',
                'img' => '/img/flags/mg.svg',
                'prefix' => '+261',
            ],
            125 => [
                'name' => 'Макао',
                'code' => 'MO',
                'mask' => '+853-____-____',
                'img' => '/img/flags/mo.svg',
                'prefix' => '+853',
            ],
            126 => [
                'name' => 'Македония',
                'code' => 'MK',
                'mask' => '+389-__-___-___',
                'img' => '/img/flags/mk.svg',
                'prefix' => '+389',
            ],
            127 => [
                'name' => 'Малави',
                'code' => 'MW',
                'mask' => '+265-_-____-____',
                'img' => '/img/flags/mw.svg',
                'prefix' => '+265',
            ],
            129 => [
                'name' => 'Мали',
                'code' => 'ML',
                'mask' => '+223-__-__-____',
                'img' => '/img/flags/ml.svg',
                'prefix' => '+223',
            ],
            130 => [
                'name' => 'Мальдивы',
                'code' => 'MV',
                'mask' => '+960-___-____',
                'img' => '/img/flags/mv.svg',
                'prefix' => '+960',
            ],
            131 => [
                'name' => 'Мальта',
                'code' => 'MT',
                'mask' => '+356-____-____',
                'img' => '/img/flags/mt.svg',
                'prefix' => '+356',
            ],
            132 => [
                'name' => 'Марокко',
                'code' => 'MA',
                'mask' => '+212-__-____-___',
                'img' => '/img/flags/ma.svg',
                'prefix' => '+212',
            ],
            133 => [
                'name' => 'Мартиника',
                'code' => 'MQ',
                'mask' => '+596(___)__-__-__',
                'img' => '/img/flags/mq.svg',
                'prefix' => '+596',
            ],
            134 => [
                'name' => 'Маршалловы Острова',
                'code' => 'MH',
                'mask' => '+692-___-____',
                'img' => '/img/flags/mh.svg',
                'prefix' => '+692',
            ],
            135 => [
                'name' => 'Мексика',
                'code' => 'MX',
                'mask' => '+52(___)___-____',
                'img' => '/img/flags/mx.svg',
                'prefix' => '+52',
            ],
            136 => [
                'name' => 'Микронезия',
                'code' => 'FM',
                'mask' => '+691-___-____',
                'img' => '/img/flags/fm.svg',
                'prefix' => '+691',
            ],
            137 => [
                'name' => 'Мозамбик',
                'code' => 'MZ',
                'mask' => '+258-__-___-___',
                'img' => '/img/flags/mz.svg',
                'prefix' => '+258',
            ],
            138 => [
                'name' => 'Молдавия',
                'code' => 'MD',
                'mask' => '+373-____-____',
                'img' => '/img/flags/md.svg',
                'prefix' => '+373',
            ],
            139 => [
                'name' => 'Монако',
                'code' => 'MC',
                'mask' => '+377(___)___-___',
                'img' => '/img/flags/mc.svg',
                'prefix' => '+377',
            ],
            140 => [
                'name' => 'Монголия',
                'code' => 'MN',
                'mask' => '+976-__-__-____',
                'img' => '/img/flags/mn.svg',
                'prefix' => '+976',
            ],
            141 => [
                'name' => 'Монтсеррат',
                'code' => 'MS',
                'mask' => '+1(664)___-____',
                'img' => '/img/flags/ms.svg',
                'prefix' => '+1664',
            ],
            142 => [
                'name' => 'Мьянма',
                'code' => 'MM',
                'mask' => '+95-__-___-___',
                'img' => '/img/flags/mm.svg',
                'prefix' => '+95',
            ],
            143 => [
                'name' => 'Намибия',
                'code' => 'NA',
                'mask' => '+264-__-___-____',
                'img' => '/img/flags/na.svg',
                'prefix' => '+264',
            ],
            144 => [
                'name' => 'Науру',
                'code' => 'NR',
                'mask' => '+674-___-____',
                'img' => '/img/flags/nr.svg',
                'prefix' => '+674',
            ],
            145 => [
                'name' => 'Непал',
                'code' => 'NP',
                'mask' => '+977-__-___-___',
                'img' => '/img/flags/np.svg',
                'prefix' => '+977',
            ],
            146 => [
                'name' => 'Нигер',
                'code' => 'NE',
                'mask' => '+227-__-__-____',
                'img' => '/img/flags/ne.svg',
                'prefix' => '+227',
            ],
            147 => [
                'name' => 'Нигерия',
                'code' => 'NG',
                'mask' => '+234(___)___-____',
                'img' => '/img/flags/ng.svg',
                'prefix' => '+234',
            ],
            148 => [
                'name' => 'Нидерланды',
                'code' => 'NL',
                'mask' => '+31-__-___-____',
                'img' => '/img/flags/nl.svg',
                'prefix' => '+31',
            ],
            149 => [
                'name' => 'Никарагуа',
                'code' => 'NI',
                'mask' => '+505-____-____',
                'img' => '/img/flags/ni.svg',
                'prefix' => '+505',
            ],
            150 => [
                'name' => 'Ниуэ',
                'code' => 'NU',
                'mask' => '+683-____',
                'img' => '/img/flags/nu.svg',
                'prefix' => '+683',
            ],
            151 => [
                'name' => 'Новая Зеландия',
                'code' => 'NZ',
                'mask' => '+64(___)___-___',
                'img' => '/img/flags/nz.svg',
                'prefix' => '+64',
            ],
            152 => [
                'name' => 'Новая Каледония',
                'code' => 'NC',
                'mask' => '+687-__-____',
                'img' => '/img/flags/nc.svg',
                'prefix' => '+687',
            ],
            153 => [
                'name' => 'Норвегия',
                'code' => 'NO',
                'mask' => '+47(___)__-___',
                'img' => '/img/flags/no.svg',
                'prefix' => '+47',
            ],
            154 => [
                'name' => 'ОАЭ',
                'code' => 'AE',
                'mask' => '+971-_-___-____',
                'img' => '/img/flags/ae.svg',
                'prefix' => '+971',
            ],
            155 => [
                'name' => 'Оман',
                'code' => 'OM',
                'mask' => '+968-__-___-___',
                'img' => '/img/flags/om.svg',
                'prefix' => '+968',
            ],
            158 => [
                'name' => 'Острова Кука',
                'code' => 'CK',
                'mask' => '+682-__-___',
                'img' => '/img/flags/ck.svg',
                'prefix' => '+682',
            ],
            159 => [
                'name' => 'Остров Норфолк',
                'code' => 'NF',
                'mask' => '+672-3__-___',
                'img' => '/img/flags/nf.svg',
                'prefix' => '+6723',
            ],
            163 => [
                'name' => 'Пакистан',
                'code' => 'PK',
                'mask' => '+92(___)___-____',
                'img' => '/img/flags/pk.svg',
                'prefix' => '+92',
            ],
            164 => [
                'name' => 'Палау',
                'code' => 'PW',
                'mask' => '+680-___-____',
                'img' => '/img/flags/pw.svg',
                'prefix' => '+680',
            ],
            165 => [
                'name' => 'Государство Палестина',
                'code' => 'PS',
                'mask' => '+970-__-___-____',
                'img' => '/img/flags/ps.svg',
                'prefix' => '+970',
            ],
            166 => [
                'name' => 'Панама',
                'code' => 'PA',
                'mask' => '+507-___-____',
                'img' => '/img/flags/pa.svg',
                'prefix' => '+507',
            ],
            167 => [
                'name' => 'Папуа — Новая Гвинея',
                'code' => 'PG',
                'mask' => '+675(___)__-___',
                'img' => '/img/flags/pg.svg',
                'prefix' => '+675',
            ],
            168 => [
                'name' => 'Парагвай',
                'code' => 'PY',
                'mask' => '+595(___)___-___',
                'img' => '/img/flags/py.svg',
                'prefix' => '+595',
            ],
            169 => [
                'name' => 'Перу',
                'code' => 'PE',
                'mask' => '+51(___)___-___',
                'img' => '/img/flags/pe.svg',
                'prefix' => '+51',
            ],
            170 => [
                'name' => 'Польша',
                'code' => 'PL',
                'mask' => '+48(___)___-___',
                'img' => '/img/flags/pl.svg',
                'prefix' => '+48',
            ],
            171 => [
                'name' => 'Португалия',
                'code' => 'PT',
                'mask' => '+351-__-___-____',
                'img' => '/img/flags/pt.svg',
                'prefix' => '+351',
            ],
            173 => [
                'name' => 'Республика Конго',
                'code' => 'CG',
                'mask' => '+242-__-___-____',
                'img' => '/img/flags/cg.svg',
                'prefix' => '+242',
            ],
            174 => [
                'name' => 'Республика Корея',
                'code' => 'KR',
                'mask' => '+82-__-___-____',
                'img' => '/img/flags/kr.svg',
                'prefix' => '+82',
            ],
            175 => [
                'name' => 'Реюньон',
                'code' => 'RE',
                'mask' => '+262-_____-____',
                'img' => '/img/flags/re.svg',
                'prefix' => '+262',
            ],
            176 => [
                'name' => 'Руанда',
                'code' => 'RW',
                'mask' => '+250(___)___-___',
                'img' => '/img/flags/rw.svg',
                'prefix' => '+250',
            ],
            177 => [
                'name' => 'Румыния',
                'code' => 'RO',
                'mask' => '+40-__-___-____',
                'img' => '/img/flags/ro.svg',
                'prefix' => '+40',
            ],
            178 => [
                'name' => 'Сальвадор',
                'code' => 'SV',
                'mask' => '+503-__-__-____',
                'img' => '/img/flags/sv.svg',
                'prefix' => '+503',
            ],
            179 => [
                'name' => 'Самоа',
                'code' => 'WS',
                'mask' => '+685-__-____',
                'img' => '/img/flags/ws.svg',
                'prefix' => '+685',
            ],
            180 => [
                'name' => 'Сан-Марино',
                'code' => 'SM',
                'mask' => '+378-____-______',
                'img' => '/img/flags/sm.svg',
                'prefix' => '+378',
            ],
            181 => [
                'name' => 'Сан-Томе и Принсипи',
                'code' => 'ST',
                'mask' => '+239-__-_____',
                'img' => '/img/flags/st.svg',
                'prefix' => '+239',
            ],
            182 => [
                'name' => 'Саудовская Аравия',
                'code' => 'SA',
                'mask' => '+966-_-___-____',
                'img' => '/img/flags/sa.svg',
                'prefix' => '+966',
            ],
            183 => [
                'name' => 'Свазиленд',
                'code' => 'SZ',
                'mask' => '+268-__-__-____',
                'img' => '/img/flags/sz.svg',
                'prefix' => '+268',
            ],
            184 => [
                'name' => 'Северные Марианские Острова',
                'code' => 'MP',
                'mask' => '+1(670)___-____',
                'img' => '/img/flags/mp.svg',
                'prefix' => '+1(670)',
            ],
            185 => [
                'name' => 'Сейшельские Острова',
                'code' => 'SC',
                'mask' => '+248-_-___-___',
                'img' => '/img/flags/sc.svg',
                'prefix' => '+248',
            ],
            189 => [
                'name' => 'Сенегал',
                'code' => 'SN',
                'mask' => '+221-__-___-____',
                'img' => '/img/flags/sn.svg',
                'prefix' => '+221',
            ],
            190 => [
                'name' => 'Сент-Винсент и Гренадины',
                'code' => 'VC',
                'mask' => '+1(784)___-____',
                'img' => '/img/flags/vc.svg',
                'prefix' => '+1784',
            ],
            191 => [
                'name' => 'Сент-Китс и Невис',
                'code' => 'KN',
                'mask' => '+1(869)___-____',
                'img' => '/img/flags/kn.svg',
                'prefix' => '+1869',
            ],
            192 => [
                'name' => 'Сент-Люсия',
                'code' => 'LC',
                'mask' => '+1(758)___-____',
                'img' => '/img/flags/lc.svg',
                'prefix' => '+1758',
            ],
            193 => [
                'name' => 'Сербия',
                'code' => 'RS',
                'mask' => '+381-__-___-____',
                'img' => '/img/flags/rs.svg',
                'prefix' => '+381',
            ],
            194 => [
                'name' => 'Сингапур',
                'code' => 'SG',
                'mask' => '+65-____-____',
                'img' => '/img/flags/sg.svg',
                'prefix' => '+65',
            ],
            195 => [
                'name' => 'Синт-Мартен',
                'code' => 'SX',
                'mask' => '+1(721)___-____',
                'img' => '/img/flags/sx.svg',
                'prefix' => '+599',
            ],
            196 => [
                'name' => 'Сирия',
                'code' => 'SY',
                'mask' => '+963-__-____-___',
                'img' => '/img/flags/sy.svg',
                'prefix' => '+963',
            ],
            197 => [
                'name' => 'Словакия',
                'code' => 'SK',
                'mask' => '+421(___)___-___',
                'img' => '/img/flags/sk.svg',
                'prefix' => '+421',
            ],
            198 => [
                'name' => 'Словения',
                'code' => 'SI',
                'mask' => '+386-__-___-___',
                'img' => '/img/flags/si.svg',
                'prefix' => '+386',
            ],
            199 => [
                'name' => 'Соломоновы Острова',
                'code' => 'SB',
                'mask' => '+677-___-____',
                'img' => '/img/flags/sb.svg',
                'prefix' => '+677',
            ],
            200 => [
                'name' => 'Сомали',
                'code' => 'SO',
                'mask' => '+252-__-___-___',
                'img' => '/img/flags/so.svg',
                'prefix' => '+252',
            ],
            201 => [
                'name' => 'Судан',
                'code' => 'SD',
                'mask' => '+249-__-___-____',
                'img' => '/img/flags/sd.svg',
                'prefix' => '+249',
            ],
            203 => [
                'name' => 'Суринам',
                'code' => 'SR',
                'mask' => '+597-___-____',
                'img' => '/img/flags/sr.svg',
                'prefix' => '+597',
            ],
            204 => [
                'name' => 'США',
                'code' => 'US',
                'mask' => '+1(___)___-____',
                'img' => '/img/flags/us.svg',
                'prefix' => '+1',
            ],
            205 => [
                'name' => 'Сьерра-Леоне',
                'code' => 'SL',
                'mask' => '+232-__-______',
                'img' => '/img/flags/sl.svg',
                'prefix' => '+232',
            ],
            206 => [
                'name' => 'Таджикистан',
                'code' => 'TJ',
                'mask' => '+992-__-___-____',
                'img' => '/img/flags/tj.svg',
                'prefix' => '+992',
            ],
            207 => [
                'name' => 'Таиланд',
                'code' => 'TH',
                'mask' => '+66-__-___-____',
                'img' => '/img/flags/th.svg',
                'prefix' => '+66',
            ],
            208 => [
                'name' => 'Танзания',
                'code' => 'TZ',
                'mask' => '+255-__-___-____',
                'img' => '/img/flags/tz.svg',
                'prefix' => '+255',
            ],
            209 => [
                'name' => 'Тёркс и Кайкос',
                'code' => 'TC',
                'mask' => '+1(649)___-____',
                'img' => '/img/flags/tc.svg',
                'prefix' => '+1(649)',
            ],
            210 => [
                'name' => 'Того',
                'code' => 'TG',
                'mask' => '+228-__-___-___',
                'img' => '/img/flags/tg.svg',
                'prefix' => '+228',
            ],
            211 => [
                'name' => 'Токелау',
                'code' => 'TK',
                'mask' => '+690-____',
                'img' => '/img/flags/tk.svg',
                'prefix' => '+690',
            ],
            212 => [
                'name' => 'Тонга',
                'code' => 'TO',
                'mask' => '+676-_____',
                'img' => '/img/flags/to.svg',
                'prefix' => '+676',
            ],
            213 => [
                'name' => 'Тринидад и Тобаго',
                'code' => 'TT',
                'mask' => '+1(868)___-____',
                'img' => '/img/flags/tt.svg',
                'prefix' => '+1868',
            ],
            214 => [
                'name' => 'Тувалу',
                'code' => 'TV',
                'mask' => '+688-2____',
                'img' => '/img/flags/tv.svg',
                'prefix' => '+688',
            ],
            215 => [
                'name' => 'Тунис',
                'code' => 'TN',
                'mask' => '+216-__-___-___',
                'img' => '/img/flags/tn.svg',
                'prefix' => '+216',
            ],
            216 => [
                'name' => 'Туркмения',
                'code' => 'TM',
                'mask' => '+993-_-___-____',
                'img' => '/img/flags/tm.svg',
                'prefix' => '+993',
            ],
            217 => [
                'name' => 'Турция',
                'code' => 'TR',
                'mask' => '+90(___)___-____',
                'img' => '/img/flags/tr.svg',
                'prefix' => '+90',
            ],
            218 => [
                'name' => 'Уганда',
                'code' => 'UG',
                'mask' => '+256(___)___-___',
                'img' => '/img/flags/ug.svg',
                'prefix' => '+256',
            ],
            219 => [
                'name' => 'Узбекистан',
                'code' => 'UZ',
                'mask' => '+998-__-___-____',
                'img' => '/img/flags/uz.svg',
                'prefix' => '+998',
            ],
            220 => [
                'name' => 'Уоллис и Футуна',
                'code' => 'WF',
                'mask' => '+681-__-____',
                'img' => '/img/flags/wf.svg',
                'prefix' => '+681',
            ],
            221 => [
                'name' => 'Уругвай',
                'code' => 'UY',
                'mask' => '+598-_-___-__-__',
                'img' => '/img/flags/uy.svg',
                'prefix' => '+598',
            ],
            222 => [
                'name' => 'Фареры',
                'code' => 'FO',
                'mask' => '+298-___-___',
                'img' => '/img/flags/fo.svg',
                'prefix' => '+298',
            ],
            223 => [
                'name' => 'Фиджи',
                'code' => 'FJ',
                'mask' => '+679-__-_____',
                'img' => '/img/flags/fj.svg',
                'prefix' => '+679',
            ],
            224 => [
                'name' => 'Филиппины',
                'code' => 'PH',
                'mask' => '+63(___)___-____',
                'img' => '/img/flags/ph.svg',
                'prefix' => '+63',
            ],
            225 => [
                'name' => 'Финляндия',
                'code' => 'FI',
                'mask' => '+358(___)___-__-__',
                'img' => '/img/flags/fi.svg',
                'prefix' => '+358',
            ],
            226 => [
                'name' => 'Фолклендские острова',
                'code' => 'FK',
                'mask' => '+500-_____',
                'img' => '/img/flags/fk.svg',
                'prefix' => '+500',
            ],
            227 => [
                'name' => 'Франция',
                'code' => 'FR',
                'mask' => '+33(___)___-___',
                'img' => '/img/flags/fr.svg',
                'prefix' => '+33',
            ],
            228 => [
                'name' => 'Французская Полинезия',
                'code' => 'PF',
                'mask' => '+689-__-__-__',
                'img' => '/img/flags/pf.svg',
                'prefix' => '+689',
            ],
            231 => [
                'name' => 'Хорватия',
                'code' => 'HR',
                'mask' => '+385-__-___-___',
                'img' => '/img/flags/hr.svg',
                'prefix' => '+385',
            ],
            232 => [
                'name' => 'ЦАР',
                'code' => 'CF',
                'mask' => '+236-__-__-____',
                'img' => '/img/flags/cf.svg',
                'prefix' => '+236',
            ],
            233 => [
                'name' => 'Чад',
                'code' => 'TD',
                'mask' => '+235-__-__-__-__',
                'img' => '/img/flags/td.svg',
                'prefix' => '+235',
            ],
            234 => [
                'name' => 'Черногория',
                'code' => 'ME',
                'mask' => '+382-__-___-___',
                'img' => '/img/flags/me.svg',
                'prefix' => '+382',
            ],
            235 => [
                'name' => 'Чехия',
                'code' => 'CZ',
                'mask' => '+420(___)___-___',
                'img' => '/img/flags/cz.svg',
                'prefix' => '+420',
            ],
            236 => [
                'name' => 'Чили',
                'code' => 'CL',
                'mask' => '+56-_-____-____',
                'img' => '/img/flags/cl.svg',
                'prefix' => '+56',
            ],
            237 => [
                'name' => 'Швейцария',
                'code' => 'CH',
                'mask' => '+41-__-___-____',
                'img' => '/img/flags/ch.svg',
                'prefix' => '+41',
            ],
            238 => [
                'name' => 'Швеция',
                'code' => 'SE',
                'mask' => '+46-__-___-____',
                'img' => '/img/flags/se.svg',
                'prefix' => '+46',
            ],
            240 => [
                'name' => 'Шри-Ланка',
                'code' => 'LK',
                'mask' => '+94-__-___-____',
                'img' => '/img/flags/lk.svg',
                'prefix' => '+94',
            ],
            241 => [
                'name' => 'Эквадор',
                'code' => 'EC',
                'mask' => '+593-__-___-____',
                'img' => '/img/flags/ec.svg',
                'prefix' => '+593',
            ],
            242 => [
                'name' => 'Экваториальная Гвинея',
                'code' => 'GQ',
                'mask' => '+240-__-___-____',
                'img' => '/img/flags/gq.svg',
                'prefix' => '+240',
            ],
            243 => [
                'name' => 'Эритрея',
                'code' => 'ER',
                'mask' => '+291-_-___-___',
                'img' => '/img/flags/er.svg',
                'prefix' => '+291',
            ],
            244 => [
                'name' => 'Эстония',
                'code' => 'EE',
                'mask' => '+372-____-____',
                'img' => '/img/flags/ee.svg',
                'prefix' => '+372',
            ],
            245 => [
                'name' => 'Эфиопия',
                'code' => 'ET',
                'mask' => '+251-__-___-____',
                'img' => '/img/flags/et.svg',
                'prefix' => '+251',
            ],
            246 => [
                'name' => 'ЮАР',
                'code' => 'ZA',
                'mask' => '+27-__-___-____',
                'img' => '/img/flags/za.svg',
                'prefix' => '+27',
            ],
            248 => [
                'name' => 'Южный Судан',
                'code' => 'SS',
                'mask' => '+211-__-___-____',
                'img' => '/img/flags/ss.svg',
                'prefix' => '+211',
            ],
            249 => [
                'name' => 'Ямайка',
                'code' => 'JM',
                'mask' => '+1(876)___-____',
                'img' => '/img/flags/jm.svg',
                'prefix' => '+1876',
            ],
            250 => [
                'name' => 'Япония',
                'code' => 'JP',
                'mask' => '+81(___)___-___',
                'img' => '/img/flags/jp.svg',
                'prefix' => '+81',
            ],
        ]);

        //
    }
}
