#!/bin/bash

chmod -R 777 src/storage
chmod -R 777 src/bootstrap/cache
chmod +x composer
chmod +x artisan
chmod +x npm
chmod +x down

mkdir -p ./docker/data/nginx-logs ./docker/data/php ./docker/data/mysql ./docker/data/redis

# Check if "nginx-proxy" is runnig:
NGINX_PROXY_CONTAINER_NAME="docker-proxy-nginx"
NGINX_PROXY_CONTAINER_ID=$(docker ps -q --filter "name=${NGINX_PROXY_CONTAINER_NAME}")
if [ -z ${NGINX_PROXY_CONTAINER_ID} ]; then
  echo "FAIL: You have to download and start '${NGINX_PROXY_CONTAINER_NAME}' container first"
  exit 1
fi

if ! [ -f ".env" ]; then
    cp .env.example .env
fi

docker-compose up -d

FIRST_INSTALL=0
if ! [ -f "src/.env" ]; then
    FIRST_INSTALL=1
    cp src/.env.example src/.env
fi

if ! [ -d "src/vendor" ]; then
    ./composer install --no-ansi
fi

if ! [ -d "src/node_modules" ]; then
    ./npm install --no-optional
    ./npm run dev
fi

./artisan migrate
# ./artisan db:seed

if [ "$FIRST_INSTALL" -eq 1 ]; then
    ./artisan job:dispatch SxGeoUpdateJob
    ./artisan storage:link
fi