name: Fix code styling

on:
  push:
    branches:
      - master
  pull_request_target:
  workflow_dispatch:
    inputs:
      php:
        description: 'Php version'
        default: "8.3"
        type: string
      message:
        description: 'Commit message'
        default: Check code styling.
        type: string

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php || 8.3 }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint in test mode (no changes)
        run: pint --test --config ./.formatters/pint.json

      - name: Install NPM dependencies
        run: npm ci -C ./src

      - name: Copy blade-formatter config to root dir
        run: |
          cp .formatters/.bladeformatterrc.json ./
          cp .formatters/.bladeignore ./

      - name: Run Blade Formatter in check mode
        run: |
          src/node_modules/.bin/blade-formatter --check-formatted \
            src/resources/views/*.blade.php \
            src/resources/views/**/*.blade.php
